apiVersion: v1
clusters:
  - cluster:
      server: https://api.rm3.7wse.p1.openshiftapps.com:6443
    name: openshift
contexts:
  - context:
      cluster: openshift
      user: idankatz
      namespace: idankatz-dev
    name: openshift-wsl
current-context: openshift-wsl
kind: Config
users:
  - name: idankatz
    user:
      token: sha256~o3d6iAFVXLQQA57NZkM1rDC7m4YcWpijbw-b7JchjK0